name: build and test
on:
    workflow_dispatch:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    buildAndTest:
        runs-on: macos-latest
        strategy:
            matrix:
                node-version: [18.x]
        env:
            METADATASUBMITTERKEY: ${{ secrets.METADATASUBMITTERKEY }}
            PROOFSUBMITTERKEY: ${{ secrets.PROOFSUBMITTERKEY }}
            PROVIDER_URL: ${{ vars.PROVIDER_URL }}
            DATASET_CONTRACT_ADDRESS: ${{ vars.DATASET_CONTRACT_ADDRESS }}
            METADATA_SUBMITTER: ${{ vars.METADATA_SUBMITTER }}
            PROOF_CONTRACT_ADDRESS: ${{ vars.PROOF_CONTRACT_ADDRESS }}
            PROOF_SUBMITTER: ${{ vars.PROOF_SUBMITTER }}
            LOTUS_API_ENDPOINT: ${{ vars.LOTUS_API_ENDPOINT }}
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                  npm install
            - name: Build
              run: |
                  npm run build
            - name: Test
              run: |
                  npm run test
