name: Version and Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    versioning:
        name: Versioning
        runs-on: macos-latest
        outputs:
            hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}
            version: ${{ steps.version.outputs.CURRENT_VERSION }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x

            - name: Install Dependencies
              run: npm install

            - name: Create Release Pull Request
              id: changesets
              uses: changesets/action@v1
              with:
                  commit: "Version Action"
                  title: "Version Action"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Get current version
              id: version
              run: echo "CURRENT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
