name: net build & Test
on:
    workflow_dispatch:
    push:
        branches: ["dev"]
    pull_request:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/*.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
                      ${{ runner.os }}-
            - name: Install dependencies
              run: |
                  npm install
            - name: Build
              run: |
                  npm run build

    Test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: |
                  npm install

            - name: Test
              run: |
                  npm test
